### ISSUE TITLE
FPA block

### ISSUE THREAD

**Issue by summerrr** [JaveyWang/PAN-pytorch#3]
In network.py 
x_gpb = nn.AvgPool2d(x.shape[2:])(x).view(x.shape[0], self.channels_cond, 1, 1)，
Assume the shape of x is Nx2048xHxW,  so after this operation，whether the shape of x is Nx2048x1x1？

**Comment by JiaweiWang-AI** [comment]
I am sorry to hear you so late. Yes, it is a global average pooling operation.
